import { ArrowUpRight, MapPin, Ticket } from "lucide-react";
import FanSignalInline from "@/components/FanSignalInline";
import { NightFooter, NightHeader } from "@/components/NightFrequencyChrome";
import { officialBrand } from "@/content/artistPlatform";
import { useSanityArtistContent } from "@/sanity/publicContent";
import "./EcosystemPages.css";
import "./VercelAssetOverrides.css";

export default function Live() { const cms = useSanityArtistContent(); const live = cms.data?.live; const status = live?.status || "NO DATE ANNOUNCED"; const actionUrl = live?.actionUrl || "#signal"; return <div className="nf-page"><NightHeader active="/live" /><main><section className="nf-page-hero" style={{ "--page-image": `url(${officialBrand.socialPreview})` } as React.CSSProperties}><div><p className="nf-page-eyebrow">LIVE / SHOW SIGNAL</p><h1>WHEN THE<br /><em>ROOM IS READY.</em></h1><p>{live?.message || "Set live, festival, dan pertemuan di lantai dansa akan ditampilkan di sini ketika tanggal diumumkan."}</p></div><div className="nf-hero-note"><span>{cms.isLoading ? "SYNCING LIVE" : "NEXT LIVE"}</span><strong>{status}</strong><a className="nf-text-button" href={actionUrl} target={live?.actionUrl ? "_blank" : undefined} rel={live?.actionUrl ? "noreferrer" : undefined}>GET FIRST NOTICE <ArrowUpRight size={15} /></a></div></section><section className="nf-live-stage"><div><p className="nf-page-eyebrow">THE LIVE LAYER</p><h2>BUILT FOR<br /><em>THE ROOM.</em></h2><p>Halaman ini siap untuk mengelola pengumuman show, venue, kota, tiket, dan informasi tur. Saat jadwal tersedia, data resmi akan menggantikan status ini.</p><a className="nf-button" href="#signal"><Ticket size={16} /> GET FIRST NOTICE</a></div><article className="nf-live-card"><span>LIVE STATUS</span><strong>{status}</strong><p><MapPin size={13} /> INDONESIA / GLOBAL</p></article></section><section className="nf-section dark-panel"><div className="nf-section-title"><div><p className="nf-page-eyebrow">BOOKING</p><h2>LET&apos;S BUILD<br /><em>THE NEXT SET.</em></h2></div><p>Untuk booking, kolaborasi, atau kebutuhan promotor, gunakan jalur langsung yang terhubung ke tim Akbar Nawasunda.</p></div><a className="nf-text-button" href="mailto:akbarnawasunda@gmail.com">BOOK / COLLABORATE <ArrowUpRight size={15} /></a></section><section className="nf-signal-block" id="signal"><div><p className="nf-page-eyebrow">FAN SIGNAL</p><h2>DON&apos;T MISS<br /><em>THE NEXT ROOM.</em></h2><p>Dapatkan informasi show lebih awal saat jadwal diumumkan.</p></div><FanSignalInline /></section></main><NightFooter /></div>; }
