import { ArrowLeft, ArrowUpRight, Disc3, Headphones, Music2 } from "lucide-react";
import { Link, useParams } from "wouter";
import { NightFooter, NightHeader } from "@/components/NightFrequencyChrome";
import { officialBrand, releases } from "@/content/artistPlatform";
import { useSanityArtistContent } from "@/sanity/publicContent";
import "./EcosystemPages.css";
import "./ArtistModules.css";
import "./ReleaseDetail.css";

const slugify = (value: string) => value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export default function ReleaseDetail() {
  const { slug = "" } = useParams<{ slug: string }>();
  const cms = useSanityArtistContent();
  const cmsRelease = (cms.data?.releases ?? []).find(item => slugify(item.title) === slug);
  const archiveRelease = releases.find(item => slugify(item.title) === slug);
  const release = cmsRelease ? { title: cmsRelease.title, year: cmsRelease.year || "—", format: cmsRelease.format || "Release", platform: cmsRelease.platform || "Official link", href: cmsRelease.url, artwork: cmsRelease.artworkUrl || archiveRelease?.image || officialBrand.socialPreview, story: cmsRelease.story, credits: cmsRelease.credits, spotifyUrl: cmsRelease.spotifyUrl, appleMusicUrl: cmsRelease.appleMusicUrl } : archiveRelease ? { ...archiveRelease, artwork: archiveRelease.image || officialBrand.socialPreview, story: undefined, credits: undefined, spotifyUrl: undefined, appleMusicUrl: undefined } : null;
  if (!release && !cms.isLoading) return <div className="nf-page"><NightHeader active="/music" /><main><section className="nf-section an-release-missing"><p className="nf-page-eyebrow">RELEASE NOT FOUND</p><h1>THIS SIGNAL<br/><em>ISN&apos;T IN THE VAULT.</em></h1><Link className="nf-button" href="/music"><ArrowLeft size={16}/> BACK TO MUSIC</Link></section></main><NightFooter /></div>;
  const links = release ? [{ label: release.platform || "Official link", href: release.href }, ...(release.spotifyUrl ? [{ label: "Spotify", href: release.spotifyUrl }] : []), ...(release.appleMusicUrl ? [{ label: "Apple Music", href: release.appleMusicUrl }] : [])] : [];
  return <div className="nf-page"><NightHeader active="/music" /><main><section className="nf-page-hero an-release-detail-hero" style={{ "--page-image": `url(${release?.artwork || officialBrand.socialPreview})` } as React.CSSProperties}><div><Link className="an-back-link" href="/music"><ArrowLeft size={14}/> BACK TO RELEASE VAULT</Link><p className="nf-page-eyebrow">RELEASE DETAIL / {release?.format || "SYNCING"}</p><h1>{release?.title || "LOADING\nRELEASE…"}</h1><p>{release ? `${release.format} · ${release.year} · ${release.platform}` : "Menghubungkan ke katalog resmi Akbar Nawasunda."}</p></div><div className="nf-hero-note"><span>OFFICIAL RELEASE</span><strong>{release?.year || "—"}</strong><a className="nf-text-button" href={release?.href || "/music"} target={release ? "_blank" : undefined} rel={release ? "noreferrer" : undefined}>LISTEN NOW <ArrowUpRight size={15}/></a></div></section><section className="nf-section an-release-detail-grid"><div className="an-release-art"><img src={release?.artwork || officialBrand.socialPreview} alt={release ? `Artwork ${release.title}` : "Release artwork loading"}/><span><Disc3 size={18}/> {release?.format || "RELEASE"}</span></div><div className="an-release-copy"><p className="nf-page-eyebrow">THE STORY</p><h2>{release?.title || "THE\nSIGNAL."}<br/><em>IN CONTEXT.</em></h2><p>{release?.story || "Cerita di balik rilisan ini akan tampil di sini ketika dipublikasikan dari AN // Studio. Sementara itu, gunakan jalur dengar resmi untuk masuk ke karya ini."}</p><div className="an-release-credits"><span>CREDITS / NOTES</span><p>{release?.credits || "Official credits have not been published yet."}</p></div></div></section><section className="nf-section dark-panel"><div className="nf-section-title"><div><p className="nf-page-eyebrow">OFFICIAL DOORS</p><h2>PRESS<br/><em>PLAY.</em></h2></div><p>Gunakan tautan resmi yang tersedia untuk mendengarkan rilisan ini.</p></div><div className="an-release-links">{links.map(link => <a key={`${link.label}-${link.href}`} href={link.href} target="_blank" rel="noreferrer"><span>{link.label}</span><Headphones size={17}/><ArrowUpRight size={15}/></a>)}<Link href={`/inquire?type=licensing&source=release`}><span>LICENSE / USE THIS TRACK</span><Headphones size={17}/><ArrowUpRight size={15}/></Link></div></section><section className="nf-section an-release-next"><p className="nf-page-eyebrow"><Music2 size={14}/> CONTINUE THE VAULT</p><Link className="nf-button" href="/music">EXPLORE ALL RELEASES <ArrowUpRight size={15}/></Link></section></main><NightFooter /></div>;
}
