import { ArrowLeft, ArrowUpRight, Disc3, Headphones, Music2 } from "lucide-react";
import { Link, useParams } from "wouter";
import { NightFooter, NightHeader } from "@/components/NightFrequencyChrome";
import { officialBrand, releases } from "@/content/artistPlatform";
import { usePublicArtistContent } from "@/content/publicContent";
import "./EcosystemPages.css";
import "./ArtistModules.css";
import "./ReleaseDetail.css";

const slugify = (value: string) => value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const rightsLabel = (format?: string) => /bootleg/i.test(format || "") ? "UNOFFICIAL EDIT · CLEARANCE REQUIRED" : /remix|rmx/i.test(format || "") ? "REMIX · CLEARANCE REQUIRED" : "CATALOG ENTRY";
const rightsAction = (format?: string) => /bootleg/i.test(format || "") ? "CLEARANCE / ASK FIRST" : "LICENSING / ASK FIRST";

export default function ReleaseDetail() {
  const { slug = "" } = useParams<{ slug: string }>();
  const cms = usePublicArtistContent();
  const cmsRelease = (cms.data?.releases ?? []).find(item => slugify(item.title) === slug);
  const archiveRelease = releases.find(item => slugify(item.title) === slug);
  const release = cmsRelease ? { title: cmsRelease.title, year: cmsRelease.year || "—", format: cmsRelease.format || "Release", platform: cmsRelease.platform || "Official link", href: cmsRelease.url, artwork: cmsRelease.artworkUrl || archiveRelease?.image || officialBrand.socialPreview, story: cmsRelease.story, credits: cmsRelease.credits, spotifyUrl: cmsRelease.spotifyUrl, appleMusicUrl: cmsRelease.appleMusicUrl, platformLinks: cmsRelease.platformLinks || [] } : archiveRelease ? { ...archiveRelease, artwork: archiveRelease.image || officialBrand.socialPreview, story: undefined, credits: undefined, spotifyUrl: undefined, appleMusicUrl: undefined, platformLinks: [] } : null;
  if (!release && !cms.isLoading) return <div className="nf-page"><NightHeader active="/music" /><main><section className="nf-section an-release-missing"><p className="nf-page-eyebrow">RILISAN TIDAK DITEMUKAN</p><h1>RILISAN<br/>TIDAK TERSEDIA.</h1><Link className="nf-button" href="/music"><ArrowLeft size={16}/> KEMBALI KE MUSIC</Link></section></main><NightFooter /></div>;
  const links = release ? [{ label: release.platform || "Official link", href: release.href }, ...release.platformLinks, ...(release.spotifyUrl ? [{ label: "Spotify", href: release.spotifyUrl }] : []), ...(release.appleMusicUrl ? [{ label: "Apple Music", href: release.appleMusicUrl }] : [])].filter(link => link.href) : [];
  return <div className="nf-page"><NightHeader active="/music" /><main><section className="nf-page-hero an-release-detail-hero" style={{ "--page-image": `url(${release?.artwork || officialBrand.socialPreview})` } as React.CSSProperties}><div><Link className="an-back-link" href="/music"><ArrowLeft size={14}/> KEMBALI KE MUSIC</Link><p className="nf-page-eyebrow">RILISAN / {release?.format || "MEMUAT"}</p><h1>{release?.title || "MEMUAT RILISAN…"}</h1><p>{release ? `${release.format} · ${release.year} · ${release.platform}` : "Memuat katalog resmi Akbar Nawasunda."}</p></div><div className="nf-hero-note"><span>{rightsLabel(release?.format)}</span><strong>{release?.year || "—"}</strong><a className="nf-text-button" href={release?.href || "/music"} target={release ? "_blank" : undefined} rel={release ? "noreferrer" : undefined}>DENGAR <ArrowUpRight size={15}/></a></div></section><section className="nf-section an-release-detail-grid"><div className="an-release-art"><img src={release?.artwork || officialBrand.socialPreview} alt={release ? `Artwork ${release.title}` : "Release artwork loading"}/><span><Disc3 size={18}/> {release?.format || "RELEASE"}</span></div><div className="an-release-copy"><p className="nf-page-eyebrow">TENTANG RILISAN</p><h2>{release?.title || "RILISAN."}</h2><p>{release?.story || "Buka rilisan ini melalui tautan resmi yang tersedia."}</p><div className="an-release-credits"><span>CREDIT</span><p>{release?.credits || "Credit resmi belum dipublikasikan."}</p></div></div></section><section className="nf-section dark-panel"><div className="nf-section-title"><div><p className="nf-page-eyebrow">DENGAR DI</p><h2>PLATFORM<br/>RESMI.</h2></div></div><div className="an-release-links release-platform-links">{links.map(link => <a key={`${link.label}-${link.href}`} href={link.href} target="_blank" rel="noreferrer"><span>{link.label}</span><Headphones size={17}/><ArrowUpRight size={15}/></a>)}<Link href={`/inquire?type=licensing&source=release`}><span>{rightsAction(release?.format)}</span><Headphones size={17}/><ArrowUpRight size={15}/></Link></div></section><section className="nf-section an-release-next"><p className="nf-page-eyebrow"><Music2 size={14}/> RILISAN LAIN</p><Link className="nf-button" href="/music">LIHAT MUSIC <ArrowUpRight size={15}/></Link></section></main><NightFooter /></div>;
}
