import { ArrowUpRight, Play } from "lucide-react";
import FanSignalInline from "@/components/FanSignalInline";
import { ArtistSignalMotion } from "@/components/ArtistSignalMotion";
import { NightFooter, NightHeader } from "@/components/NightFrequencyChrome";
import { officialBrand, videos } from "@/content/artistPlatform";
import { useSanityArtistContent } from "@/sanity/publicContent";
import "./EcosystemPages.css";
import "./OfficialEmbeds.css";
import "./MediaEnhancements.css";

const officialVideos = [{ id: "rv4DK8nVWd0", title: "Garam dan Madu × Backpacker" }, { id: "BOTdDcx31Zc", title: "Akbar Nawasunda — Official Visual" }];
const thumbnailFor = (id: string) => `https://i.ytimg.com/vi/${id}/hqdefault.jpg`;

export default function Visuals() {
  const cms = useSanityArtistContent();
  const cmsVisuals = cms.data?.visuals ?? [];
  const embedded = cmsVisuals.filter(item => item.youtubeId).slice(0, 2).map(item => ({ id: item.youtubeId!, title: item.title }));
  const players = embedded.length ? embedded : officialVideos;
  const archive = cmsVisuals.length ? cmsVisuals.map(item => ({ title: item.title, label: item.label || "OFFICIAL VISUAL", href: item.url || (item.youtubeId ? `https://youtu.be/${item.youtubeId}` : "https://www.youtube.com/@akbarnawasunda"), image: item.imageUrl || (item.youtubeId ? thumbnailFor(item.youtubeId) : officialBrand.socialPreview) })) : videos;
  return <div className="nf-page"><NightHeader active="/visuals" /><main><section className="nf-page-hero" style={{ "--page-image": `url(${officialBrand.socialPreview})` } as React.CSSProperties}><div><p className="nf-page-eyebrow">VISUALS / MOTION ARCHIVE</p><h1>SEE THE<br /><em>SOUND MOVE.</em></h1><p>Visual dan DJ remix dari channel resmi Akbar Nawasunda—bisa diputar langsung di sini.</p></div><ArtistSignalMotion className="music-hero-motion" /><div className="nf-hero-note"><span>{cms.isLoading ? "SYNCING VISUALS" : "OFFICIAL CHANNEL"}</span><strong>AKBAR NAWASUNDA</strong><a className="nf-text-button" href="https://www.youtube.com/@akbarnawasunda" target="_blank" rel="noreferrer">VISIT YOUTUBE <ArrowUpRight size={15} /></a></div></section><section className="nf-section"><div className="nf-section-title"><div><p className="nf-page-eyebrow">WATCH / SHARE / REPEAT</p><h2>THE FRAME<br /><em>HOLDS THE BEAT.</em></h2></div><p>Pilihan visual dari channel YouTube resmi; tekan play untuk menonton tanpa berpindah halaman.</p></div><div className="nf-video-embed-grid">{players.map(video => <article className="nf-video-embed" key={video.id}><a className="nf-source-thumbnail" href={`https://youtu.be/${video.id}`} target="_blank" rel="noreferrer"><img src={thumbnailFor(video.id)} alt={`Thumbnail resmi YouTube ${video.title}`} /></a><iframe title={`YouTube: ${video.title}`} src={`https://www.youtube-nocookie.com/embed/${video.id}`} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /><p>{video.title}</p><a className="nf-embed-link" href={`https://youtu.be/${video.id}`} target="_blank" rel="noreferrer">OPEN ON YOUTUBE <ArrowUpRight size={13} /></a></article>)}</div></section><section className="nf-section dark-panel"><div className="nf-section-title"><div><p className="nf-page-eyebrow">MORE FROM THE ARCHIVE</p><h2>KEEP<br /><em>WATCHING.</em></h2></div><p>{cmsVisuals.length ? "Arsip ini sedang ditarik dari Akbar Nawasunda CMS." : "Masuk ke channel resmi untuk melihat seluruh arsip, set, dan visual baru."}</p></div><div className="nf-visual-grid">{archive.map(video => <a key={video.title} className="nf-visual-card" href={video.href} target="_blank" rel="noreferrer"><img src={video.image} alt="Akbar Nawasunda official visual artwork" /><div><span>{video.label}</span><h3>{video.title}</h3><p className="nf-text-button">WATCH NOW <Play size={14} fill="currentColor" /></p></div></a>)}</div></section><section className="nf-signal-block" id="signal"><div><p className="nf-page-eyebrow">FAN SIGNAL</p><h2>NEW VISUALS,<br /><em>DIRECT TO YOU.</em></h2><p>Masuk untuk mendapatkan pemberitahuan ketika visual atau DJ set berikutnya dirilis.</p></div><FanSignalInline /></section></main><NightFooter /></div>;
}
